global-message: GIT-Servidor de configuracion levantado Gaaa!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concesionario2
    username: root
    password: Russleny1?
    driver-class-name: com.mysql.cj.jdbc.Driver
